openapi: 3.0.3
info:
  title: Category API
  version: 1.0.0
paths:
  /api/categories:
    get:
      summary: List categories
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategoryGetAllRequestDTO'
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
        - name: size
          in: query
          required: false
          schema:
            type: integer
        - name: sort
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Category page
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoryGetAllResponseDTO'
  /api/categories/search:
    get:
      summary: Search categories
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CategorySearchRequestDTO'
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
        - name: page
          in: query
          required: false
          schema:
            type: integer
        - name: size
          in: query
          required: false
          schema:
            type: integer
        - name: sort
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Category search results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategorySearchResponseDTO'
components:
  schemas:
    CategoryGetAllRequestDTO:
      type: object
      properties:
        page:
          type: integer
        size:
          type: integer
        sort:
          type: string
    CategoryGetAllResponseDTO:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/CategoryResponseDTO'
        pageNumber:
          type: integer
        pageSize:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
    CategorySearchRequestDTO:
      type: object
      properties:
        query:
          type: string
        page:
          type: integer
        size:
          type: integer
        sort:
          type: string
    CategorySearchResponseDTO:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/CategoryResponseDTO'
        pageNumber:
          type: integer
        pageSize:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
    CategoryResponseDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        uuid:
          type: string
        name:
          type: string
        description:
          type: string
