openapi: 3.0.3
info:
  title: Device API
  version: 1.0.0
paths:
  /api/v1/user/devices/{id}:
    get:
      summary: Get a device by ID
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceGetByIdRequestDTO'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Device found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceGetByIdResponseDTO'
    put:
      summary: Update a device by ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceUpdateRequestDTO'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Device updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceUpdateResponseDTO'
    delete:
      summary: Delete a device by ID
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceDeleteRequestDTO'
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Device deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceDeleteResponseDTO'
  /api/v1/user/devices:
    get:
      summary: List devices
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceGetPageBasicRequestDTO'
      parameters:
        - name: q
          in: query
          required: false
          schema:
            type: string
        - name: page
          in: query
          required: false
          schema:
            type: integer
        - name: size
          in: query
          required: false
          schema:
            type: integer
        - name: sort
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Device page
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceGetPageBasicResponseDTO'
    post:
      summary: Create a device
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceCreateRequestDTO'
      responses:
        '201':
          description: Device created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceCreateResponseDTO'
  /api/v1/user/devices/with-stock:
    get:
      summary: List devices with stock
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceGetPageWithStockRequestDTO'
      parameters:
        - name: q
          in: query
          required: false
          schema:
            type: string
        - name: page
          in: query
          required: false
          schema:
            type: integer
        - name: size
          in: query
          required: false
          schema:
            type: integer
        - name: sort
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Device page with stock
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceGetPageWithStockResponseDTO'
  /api/v1/user/devices/by-uuid/{uuid}:
    get:
      summary: Get a device by UUID
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceGetByUuidRequestDTO'
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Device found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeviceGetByUuidResponseDTO'
components:
  schemas:
    DeviceGetByIdRequestDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
    DeviceGetByIdResponseDTO:
      type: object
      properties:
        device:
          $ref: '#/components/schemas/DeviceResponseDTO'
    DeviceGetPageBasicRequestDTO:
      type: object
      properties:
        q:
          type: string
        page:
          type: integer
        size:
          type: integer
        sort:
          type: string
    DeviceGetPageBasicResponseDTO:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/DeviceListDTO'
        pageNumber:
          type: integer
        pageSize:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
    DeviceGetPageWithStockRequestDTO:
      type: object
      properties:
        q:
          type: string
        page:
          type: integer
        size:
          type: integer
        sort:
          type: string
    DeviceGetPageWithStockResponseDTO:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/DeviceListWithStockDTO'
        pageNumber:
          type: integer
        pageSize:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
    DeviceGetByUuidRequestDTO:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
    DeviceGetByUuidResponseDTO:
      type: object
      properties:
        device:
          $ref: '#/components/schemas/DeviceResponseDTO'
    DeviceCreateRequestDTO:
      type: object
      properties:
        device:
          $ref: '#/components/schemas/DeviceRequestDTO'
    DeviceCreateResponseDTO:
      type: object
      properties:
        device:
          $ref: '#/components/schemas/DeviceResponseDTO'
    DeviceUpdateRequestDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        device:
          $ref: '#/components/schemas/DeviceRequestDTO'
    DeviceUpdateResponseDTO:
      type: object
      properties:
        device:
          $ref: '#/components/schemas/DeviceResponseDTO'
    DeviceDeleteRequestDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
    DeviceDeleteResponseDTO:
      type: object
      properties:
        message:
          type: string
    DeviceRequestDTO:
      type: object
      properties:
        serialNumber:
          type: string
        name:
          type: string
        description:
          type: string
        photoUrl:
          type: string
        vendorId:
          type: integer
          format: int64
        purchasePrice:
          type: number
          format: double
        purchaseDate:
          type: string
          format: date
        categoryIds:
          type: array
          items:
            type: integer
            format: int64
        maintenanceStatusId:
          type: integer
          format: int64
        stockRequestDTO:
          $ref: '#/components/schemas/StockRequestDTO'
    DeviceResponseDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        uuid:
          type: string
          format: uuid
        serialNumber:
          type: string
        name:
          type: string
        description:
          type: string
        photoUrl:
          type: string
        vendorId:
          type: integer
          format: int64
        purchasePrice:
          type: number
          format: double
        purchaseDate:
          type: string
          format: date
        categoryIds:
          type: array
          items:
            type: integer
            format: int64
        maintenanceStatusId:
          type: integer
          format: int64
        createDate:
          type: string
          format: date-time
        updateDate:
          type: string
          format: date-time
    DeviceListDTO:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
        serialNumber:
          type: string
    DeviceListWithStockDTO:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
        serialNumber:
          type: string
        stockCount:
          type: number
          format: double
        stockUnitType:
          $ref: '#/components/schemas/StockUnitType'
        vendorName:
          type: string
    StockRequestDTO:
      type: object
      properties:
        stockUnitType:
          $ref: '#/components/schemas/StockUnitType'
        stockCount:
          type: number
          format: double
        isFractional:
          type: boolean
    StockUnitType:
      type: string
      enum:
        - GRAM
        - MILLILITER
        - PIECES
