openapi: 3.0.3
info:
  title: Maintenance Status API
  version: 1.0.0
paths:
  /api/maintenance-statuses:
    get:
      summary: List maintenance statuses
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaintenanceStatusGetAllRequestDTO'
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
        - name: size
          in: query
          required: false
          schema:
            type: integer
        - name: sort
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Maintenance status page
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaintenanceStatusGetAllResponseDTO'
  /api/maintenance-statuses/search:
    get:
      summary: Search maintenance statuses
      requestBody:
        required: false
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MaintenanceStatusSearchRequestDTO'
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
        - name: page
          in: query
          required: false
          schema:
            type: integer
        - name: size
          in: query
          required: false
          schema:
            type: integer
        - name: sort
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Maintenance status search results
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaintenanceStatusSearchResponseDTO'
components:
  schemas:
    MaintenanceStatusGetAllRequestDTO:
      type: object
      properties:
        page:
          type: integer
        size:
          type: integer
        sort:
          type: string
    MaintenanceStatusGetAllResponseDTO:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/MaintenanceStatusResponseDTO'
        pageNumber:
          type: integer
        pageSize:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
    MaintenanceStatusSearchRequestDTO:
      type: object
      properties:
        query:
          type: string
        page:
          type: integer
        size:
          type: integer
        sort:
          type: string
    MaintenanceStatusSearchResponseDTO:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/MaintenanceStatusResponseDTO'
        pageNumber:
          type: integer
        pageSize:
          type: integer
        totalElements:
          type: integer
          format: int64
        totalPages:
          type: integer
    MaintenanceStatusResponseDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        uuid:
          type: string
        name:
          type: string
        description:
          type: string
